name: 'Rustセットアップ'
description: 'Rustツールチェーンとその依存関係のセットアップ'

inputs:
  toolchain:
    description: 'Rustのツールチェーン'
    required: false
    default: 'stable'
  components:
    description: 'インストールするコンポーネント'
    required: false
    default: 'rustfmt, clippy'
  cache-key:
    description: 'キャッシュのキー'
    required: false
    default: 'rust-setup'

runs:
  using: "composite"
  steps:
    # 必要なツールをインストール
    - name: 依存ツールインストール
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y curl wget

    # justを直接インストール
    - name: Justインストール
      uses: extractions/setup-just@v3

    # rustupを使用
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ inputs.toolchain }}
        override: true
        components: ${{ inputs.components }}
