name: 'Build Native Module'
description: 'Sets up environment, builds the native module using napi-rs, and uploads the artifact.'
inputs:
  name:
    description: 'Platform identifier (e.g., linux-x64-gnu)'
    required: true
  os:
    description: 'Runner OS (e.g., ubuntu-latest)'
    required: true
  target:
    description: 'Rust target triple (e.g., x86_64-unknown-linux-gnu)'
    required: true
  artifact-name-prefix:
    description: 'Prefix for the artifact name'
    required: false
    default: 'pr-binaries'
  arch:
    description: 'Architecture (e.g., x64, arm64)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Rustツールチェインのセットアップ
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        targets: ${{ inputs.target }}

    - name: Rustターゲットの追加
      shell: bash
      run: rustup target add ${{ inputs.target }}

    - name: Node.js設定
      uses: ./.github/actions/node-setup
      with:
        node-version: '' # Use project's default
        package-path: '.'

    - name: Linux 依存関係のインストールと設定
      if: startsWith(inputs.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt-get update -y
        if [[ "${{ inputs.target }}" == "x86_64-unknown-linux-gnu" ]]; then
          echo "Installing dependencies for x86_64 native compilation..."
          sudo apt-get install -y --no-install-recommends \
            pkg-config \
            libx11-dev \
            libxtst-dev \
            libdbus-1-dev # electron-rs/cargo-build requires this
        fi

    - name: バイナリビルド (napi build)
      shell: bash
      run: |
        set -ex
        echo "Running napi build for target: ${{ inputs.target }}"
        if [[ "${{ inputs.os }}" == "macos-latest" && "${{ inputs.target }}" == "x86_64-apple-darwin" && "$(uname -m)" == "arm64" ]]; then
          echo "Setting up cross-compilation from ARM64 to x86_64 on macOS..."
          export CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER="$(xcrun --find clang)"
          export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
          export MACOSX_DEPLOYMENT_TARGET=$(xcrun --sdk macosx --show-sdk-platform-version)
        fi
        
        pnpm exec napi build --platform --release --target ${{ inputs.target }}

    - name: List built files
      shell: bash
      run: ls -la *.node

    - name: 成果物をアップロード
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name-prefix }}-${{ inputs.name }}
        path: "*.node" 