name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract release notes
        id: extract-release-notes
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          # git-cliff形式のCHANGELOGからリリースノートを抽出
          VERSION_NUM=${VERSION#v}
          CHANGELOG_SECTION=$(awk -v ver="$VERSION_NUM" '
            /^## \['$VERSION_NUM'\]/ {
              in_section = 1;
              print;
              next;
            }
            /^## \[/ {
              if (in_section) exit;
            }
            in_section { print }
          ' CHANGELOG.md || echo "リリースノートが見つかりません")
          
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG_SECTION" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.extract-release-notes.outputs.version }}
          body: ${{ steps.extract-release-notes.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 