name: Debug Linux ARM64 Setup

on:
  # 手動実行用トリガー
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  debug-setup:
    name: Debug linux-arm64 Setup
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: apt-get update (初回)
        run: sudo apt-get update -y

      - name: Add arm64 architecture
        run: sudo dpkg --add-architecture arm64

      - name: apt-get update (アーキテクチャ追加後)
        run: sudo apt-get update -y
        # ここで失敗する場合は、リポジトリソースの確認やキャッシュクリアが必要かもしれない

      - name: Install arm64 cross-compilation tools
        run: |
          echo "Attempting to install cross-compilation tools..."
          sudo apt-get install -y --no-install-recommends \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libc6-dev-arm64-cross
          echo "Installation command finished."

      - name: Verify installed packages
        run: |
          echo "Verifying installed packages..."
          dpkg -l | grep -E 'gcc-aarch64-linux-gnu|g++-aarch64-linux-gnu|libc6-dev-arm64-cross' || echo "Some packages might be missing."
          echo "Verification finished."

      - name: Setup Rust
        uses: ./.github/actions/setup-rust # 既存の Rust セットアップアクションを使用
        with:
          toolchain: stable

      - name: Add Rust target aarch64-unknown-linux-gnu
        run: rustup target add aarch64-unknown-linux-gnu
        shell: bash

      - name: Check Rust target list
        run: rustup target list --installed
        shell: bash 