name: PR Build Check

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    # paths:
    #   - 'src/**'
    #   - 'native/**'
    #   - 'npm/**'
    #   - 'package.json'
    #   - 'pnpm-lock.yaml'
    #   - 'Cargo.toml'
    #   - 'Cargo.lock'

jobs:
  cross-build:
    name: クロスビルド
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Rustツールチェインのセットアップ
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Node.js設定
        uses: ./.github/actions/node-setup
        with:
          node-version: ''
          package-path: '.'
      
      - name: Dockerセットアップ
        uses: docker/setup-buildx-action@v2
      
      - name: Crossのインストール
        run: cargo install cross
      
      - name: クロスビルド実行
        run: |
          # Linux x64向け
          cross build --target x86_64-unknown-linux-gnu
          
          # Linux ARM64向け
          cross build --target aarch64-unknown-linux-gnu
          
          # macOS x64向け
          cross build --target x86_64-apple-darwin
          
          # macOS ARM64向け
          cross build --target aarch64-apple-darwin
          
          # Windows x64向け
          cross build --target x86_64-pc-windows-msvc
      
      - name: ビルド成果物の収集
        run: |
          mkdir -p artifacts/pr-binaries-linux-x64 artifacts/pr-binaries-linux-arm64 artifacts/pr-binaries-macos-x64 artifacts/pr-binaries-macos-arm64 artifacts/pr-binaries-windows-x64
          
          # 適切なパスにビルド成果物をコピー
          find target/x86_64-unknown-linux-gnu/debug -name "electron-pan-clip.*" -exec cp {} artifacts/pr-binaries-linux-x64/ \;
          find target/aarch64-unknown-linux-gnu/debug -name "electron-pan-clip.*" -exec cp {} artifacts/pr-binaries-linux-arm64/ \;
          find target/x86_64-apple-darwin/debug -name "electron-pan-clip.*" -exec cp {} artifacts/pr-binaries-macos-x64/ \;
          find target/aarch64-apple-darwin/debug -name "electron-pan-clip.*" -exec cp {} artifacts/pr-binaries-macos-arm64/ \;
          find target/x86_64-pc-windows-msvc/debug -name "electron-pan-clip.*" -exec cp {} artifacts/pr-binaries-windows-x64/ \;
          
          # 成果物の確認
          find artifacts -type f | sort
      
      - name: 成果物のアップロード
        uses: actions/upload-artifact@v4
        with:
          path: artifacts
      
  # ビルド結果の検証
  verify-binaries:
    name: バイナリ検証
    needs: cross-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Node.js設定
        uses: ./.github/actions/node-setup
        with:
          node-version: ''
          package-path: '.'
      
      # ビルド成果物をダウンロード
      - name: 成果物をダウンロード
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      # 成果物を正しい場所にコピー
      - name: 成果物を配置
        shell: bash
        run: |
          mkdir -p npm/linux-x64-gnu npm/linux-arm64-gnu npm/darwin-x64 npm/darwin-arm64 npm/win32-x64-msvc
          
          # Linux x64
          find artifacts -name "electron-pan-clip.linux-x64-gnu.node" -exec cp {} npm/linux-x64-gnu/ \; || echo "Warning: linux-x64-gnu バイナリが見つかりませんでした"
          
          # Linux ARM64
          find artifacts -name "electron-pan-clip.linux-arm64-gnu.node" -exec cp {} npm/linux-arm64-gnu/ \; || echo "Warning: linux-arm64-gnu バイナリが見つかりませんでした"
          
          # macOS x64
          find artifacts -name "electron-pan-clip.darwin-x64.node" -exec cp {} npm/darwin-x64/ \; || echo "Warning: darwin-x64 バイナリが見つかりませんでした"
          
          # macOS ARM64
          find artifacts -name "electron-pan-clip.darwin-arm64.node" -exec cp {} npm/darwin-arm64/ \; || echo "Warning: darwin-arm64 バイナリが見つかりませんでした"
          
          # Windows x64
          find artifacts -name "electron-pan-clip.win32-x64-msvc.node" -exec cp {} npm/win32-x64-msvc/ \; || echo "Warning: win32-x64-msvc バイナリが見つかりませんでした"
          
          # 成果物の確認
          find npm -type f | sort
      
      # バイナリ検証
      - name: バイナリ検証
        run: |
          FOUND_COUNT=$(find npm -type f -name "*.node" | wc -l)
          echo "見つかったバイナリ数: $FOUND_COUNT"
          if [ $FOUND_COUNT -eq 0 ]; then
            echo "エラー: バイナリが1つも見つかりません！"
            exit 1
          fi
          node scripts/verify-binaries.js || {
            echo "警告: バイナリ検証で一部問題が見つかりました"
            exit 1
          } 