name: PR Build Check

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    # paths:
    #   - 'src/**'
    #   - 'native/**'
    #   - 'npm/**'
    #   - 'package.json'
    #   - 'pnpm-lock.yaml'
    #   - 'Cargo.toml'
    #   - 'Cargo.lock'

jobs:
  # 各プラットフォーム向けのバイナリをビルド
  build-binaries:
    name: バイナリビルドチェック (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # 一つのビルドが失敗しても他を続行
      matrix:
        include:
          - name: linux-x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            setup-script: ""
          - name: linux-arm64
            os: ubuntu-22.04
            target: aarch64-unknown-linux-gnu
            setup-script: |
              echo "Updating package list..."
              sudo apt-get update -y
              echo "Adding arm64 architecture..."
              sudo dpkg --add-architecture arm64
              echo "Updating package list again..."
              sudo apt-get update -y
              echo "Installing for x11..."
              sudo apt-get install libxss-dev -y
              echo "Adding Rust target..."
              rustup target add aarch64-unknown-linux-gnu
          - name: macos-x64
            os: macos-latest
            target: x86_64-apple-darwin
            setup-script: "rustup target add x86_64-apple-darwin"
          - name: macos-arm64
            os: macos-latest
            target: aarch64-apple-darwin
            setup-script: "rustup target add aarch64-apple-darwin"
          - name: windows-x64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            setup-script: ""
    
    steps:
      - uses: actions/checkout@v3
      
      # 特定のターゲット向けにビルド
      - name: バイナリビルド
        uses: ./.github/actions/build-binaries
        with:
          name: ${{ matrix.name }}
          os: ${{ matrix.os }}
          target: ${{ matrix.target }}
          setup-script: ${{ matrix.setup-script }}
          artifact-name-prefix: 'pr-binaries'
  
  # ビルド結果の検証
  verify-binaries:
    name: バイナリ検証
    needs: build-binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Node.js設定
        uses: ./.github/actions/node-setup
        with:
          node-version: ''
          package-path: '.'
      
      # ビルド成果物をダウンロード
      - name: 成果物をダウンロード
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      # 成果物を正しい場所にコピー
      - name: 成果物を配置
        shell: bash
        run: |
          mkdir -p npm/linux-x64-gnu npm/linux-arm64-gnu npm/darwin-x64 npm/darwin-arm64 npm/win32-x64-msvc
          
          # Linux x64
          find artifacts/pr-binaries-linux-x64 -name "electron-pan-clip.linux-x64-gnu.node" -exec cp {} npm/linux-x64-gnu/ \; || echo "Warning: linux-x64-gnu バイナリが見つかりませんでした"
          
          # Linux ARM64
          find artifacts/pr-binaries-linux-arm64 -name "electron-pan-clip.linux-arm64-gnu.node" -exec cp {} npm/linux-arm64-gnu/ \; || echo "Warning: linux-arm64-gnu バイナリが見つかりませんでした"
          
          # macOS x64
          find artifacts/pr-binaries-macos-x64 -name "electron-pan-clip.darwin-x64.node" -exec cp {} npm/darwin-x64/ \; || echo "Warning: darwin-x64 バイナリが見つかりませんでした"
          
          # macOS ARM64
          find artifacts/pr-binaries-macos-arm64 -name "electron-pan-clip.darwin-arm64.node" -exec cp {} npm/darwin-arm64/ \; || echo "Warning: darwin-arm64 バイナリが見つかりませんでした"
          
          # Windows x64
          find artifacts/pr-binaries-windows-x64 -name "electron-pan-clip.win32-x64-msvc.node" -exec cp {} npm/win32-x64-msvc/ \; || echo "Warning: win32-x64-msvc バイナリが見つかりませんでした"
          
          # 成果物の確認
          find npm -type f | sort
      
      # バイナリ検証
      - name: バイナリ検証
        run: |
          FOUND_COUNT=$(find npm -type f -name "*.node" | wc -l)
          echo "見つかったバイナリ数: $FOUND_COUNT"
          if [ $FOUND_COUNT -eq 0 ]; then
            echo "エラー: バイナリが1つも見つかりません！"
            exit 1
          fi
          node scripts/verify-binaries.js || {
            echo "警告: バイナリ検証で一部問題が見つかりました"
            exit 1
          } 