name: 'Issue Link with PR Creator Assignment'
on:
  pull_request:
    types: [opened]

jobs:
  issue-link-with-pr-creator-assignment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Add issue links and assign PR creator to issue
        uses: tkt-actions/add-issue-links@v1.9.1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          branch-prefix: ''
          position: 'top'
          resolve: 'true'
          link-style: 'comment'
          assign-pr-creator-to-issue: 'true'
